### ISSUE TITLE
Context menu: right clicking outside the menu should close the menu

### ISSUE THREAD

**Issue by janluke** [jcoreio/material-ui-popup-state#117]
To reproduce:
1. Go to "Context menu" section in https://jcoreio.github.io/material-ui-popup-state/ (unfortunately the anchor is broken, so can't link the section)
2. Right click on the button triggers a context menu as expected
3. Right click outside the button 
  - current behaviour: the context menu remains open, the browser context menu gets open
  - expected behaviour: the context menu gets closed, the browser context menu gets open

Other case:
- Repeat steps 1 and 2
- Right click on the button again
  - current behaviour: the context menu remains open, the browser context menu gets open
  - expected behaviour: the context menu is reopened in the new position

**Comment by jedwards1211** [comment]
Now that I think about it, reopening in the new position would be inconsistent with the left-click behavior in `material-ui-popup-state` and all of the core [MUI Menu examples](https://mui.com/material-ui/react-menu/).  In both the left click and right click examples on that page, while the menu is open, another click outside the menu just closes it.

I've matched that behavior with 5.0.5 and I don't think I should differ from the "standard" MUI behavior, at least unless I make possible to pass some flag to change to a non-standard behavior.  Getting the behavior you want would be finicky because open Menus/Popovers intercept clicks anywhere on the screen.  So I'll think for awhile about if there would be a sane way to do it...

**Comment by umbertod** [comment]
This is causing the menu to close when right-clicking its own content.

While navigating a right-click is a standard to open a link into a new tab/window.

**Comment by gitmaru0** [comment]
I am having trouble with the right-click functionality being blocked on the ListItem component.
Is it possible to modify it so that it behaves like the other buttons, except for Context-Menu type buttons?

**Comment by jedwards1211** [comment]
Oof, I forgot to revert my fix for this issue.  Yep definitely considering my last comment and the issues y'all are facing, this change was a mistake.  Will get out a release in a moment...

**Comment by jedwards1211** [comment]
Okay @gitmaru0 @umbertod this has been reverted in 5.0.9

**Comment by gitmaru0** [comment]
Thank you for the speedy fix!
