### ISSUE TITLE
Class constructor PopupState cannot be invoked without 'new'

### ISSUE THREAD

**Issue by newsiberian** [jcoreio/material-ui-popup-state#2]
Hi, can't use this package because of this error:
![screenshot_20181109_181450](https://user-images.githubusercontent.com/11130487/48259714-613f0400-e44b-11e8-93dc-57f2c38f74de.png)

Any idea how can I solve this?

**Comment by jedwards1211** [comment]
Sorry for the delay, GitHub didn't automatically add me as a watcher 😞 
Can you post the code that triggered this error?  Do you get the error without using `react-hot-loader`?

**Comment by jedwards1211** [comment]
@newsiberian are you using `awesome-typescript-loader`?

**Comment by newsiberian** [comment]
Hi, @jedwards1211, I'm sorry, I'm decide to not use this package because of this error. No, I'm not using this `awesome-typescript-loader`. I do not remember in which app I tried to use your app. One of them uses `react-hot-loader`, another not.

**Comment by jedwards1211** [comment]
Okay.  It's possible that this was caused by webpack or whatever bundler you were using not being configured to transpile this package, though if so I don't exactly understand why.  It seems like it must be something like that: https://stackoverflow.com/questions/44625868/es6-babel-class-constructor-cannot-be-invoked-without-new
