### ISSUE TITLE
aria-controls for menus

### ISSUE THREAD

**Issue by dantman** [jcoreio/material-ui-popup-state#23]
The MUI documentation appears to suggest that a Button should use `aria-controls` to indicate the Menu it is connected to. However this library always uses `aria-owns` instead.

https://material-ui.com/components/menus/#menus

I'm not sure about other screen readers. However trying VoiceOver on Chrome I do notice a stark difference. With `aria-controls` I am taken to the first menu item but with this library's `aria-owns` I am stuck outside of the menu in a bad state.

**Comment by jedwards1211** [comment]
Okay, thanks for bringing this up, they probably fixed the recommendation in MUI since I made this...I should get used to using VoiceOver.

**Comment by jedwards1211** [comment]
FWIW even on the MUI website VoiceOver isn't working very well for me, clicking the very first open menu button doesn't take VoiceOver straight into the menu.  I think it has to do with the menu element not existing before it's opened, because another example where the menu element preexists seems to work better with VoiceOver.

In any case, I pushed a change to use `aria-controls`.

**Comment by dantman** [comment]
Thanks, my user menu is already working a bit better; at least for getting into the menu. Now I just have to fix getting out of it myself.
