### ISSUE TITLE
bindHover almost working

### ISSUE THREAD

**Issue by aress31** [jcoreio/material-ui-popup-state#29]
I am facing a problem with the `bindHover` hook, it all works on enter but when I leave the `MenuItem` I hovered on, the `Menu` does not automatically close:

![image](https://user-images.githubusercontent.com/11601622/81998005-502b1080-9649-11ea-90d4-cdc059fc4141.png)

I am using the following versions of `Material-UI`:
- "@material-ui/core": "^4.9.14",
- "@material-ui/icons": "^4.9.1",
- "@material-ui/styles": "^4.9.14"

Might be related to https://github.com/jcoreio/material-ui-popup-state/issues/9.

**Comment by jedwards1211** [comment]
Is your `uid` function returning something different each time for the same input route?

**Comment by aress31** [comment]
Yes it does return a unique random id for each iterated route.

**Comment by jedwards1211** [comment]
If it's different every time that might explain why mouse leave isn't working.  When the mouse enters the hover element, it opens the menu, which makes your component rerender.  When you render the hover element with a different key, React replaces the actual DOM element with a new one, so the original element that got the enter event is gone.  I'm not sure if the new element can get a leave event in that case?

**Comment by aress31** [comment]
I'll try to change the key to one that is consistent accross re-render and will let you know how it works out.

**Comment by roman-sereda** [comment]
same issue

**Comment by jedwards1211** [comment]
I didn't think to check back on this, I released some changes, did y'all try upgrading?

**Comment by brad-decker** [comment]
Having same issue with latest.

**Comment by jedwards1211** [comment]
Would it be possible to make a codesandbox to reproduce your issue?  Here's the Material-UI codesandbox template: https://codesandbox.io/s/material-ui-issue-dh2yh?file=/src/Demo.js

In OP's case it seemed to be caused by the menu items being unintentionally remounted on each render (according to a code sample in a different issue), so that's one thing to check for.

**Comment by brad-decker** [comment]
Will do in the morning and follow up!

**Comment by brad-decker** [comment]
@jedwards1211 I created a minimal example here: https://codesandbox.io/s/friendly-almeida-eqgmn?fontsize=14&hidenavigation=1&theme=dark

**Comment by jedwards1211** [comment]
Oh man, I completely forgot about the workarounds I had created for hover cases... 😂

In this case you need to
```
import Menu from 'material-ui-popup-state/HoverMenu'
```
or 
```
import Popover from 'material-ui-popup-state/HoverPopover'
```

This is because Material-UI `Modal` has a bad design where it blocks all pointer events from getting through to the components below, requiring a [messy workaround](https://github.com/jcoreio/material-ui-popup-state/blob/master/src/hoverWorkaround.js).

I'll fix the examples in the README and make this clearer...sorry for the confusion!
