### ISSUE TITLE
Can't navigate with up/down on keyboard if children of Hover Menu are custom components

### ISSUE THREAD

**Issue by alexplumb** [jcoreio/material-ui-popup-state#69]
I'm looking for guidance on how to resolve this. I've created a reusable wrapper component for the popupstate hook as well as custom components for the menu items. No matter what I do, I can't make a menu keyable unless it has MenuItem as a direct child - even if the custom component returns a MenuItem and forwards a ref.

I've created a minimal reproduction here: https://codesandbox.io/s/sleepy-wood-u6pnj?file=/src/App.js

There are three buttons in this repo:
1. First button has three custom children (not keyable)
2. Second button has one MenuItem and two custom children (keyable)
3. Third button is from the demo (keyable)

**Comment by jedwards1211** [comment]
If you forward props it *seems* to fix the issue:

```js
export const HoverPopperItem = React.forwardRef(
  ({ id, label, ...props }, ref) => {
    return (
      <MenuItem id={id} ref={ref} {...props}>
        {label}
      </MenuItem>
    );
  }
);
```

However I'm not sure if everything works when passing wrapper components.  I did see in the code that passing fragments isn't supported.  I believe this is the main MUI issue about problems like this: https://github.com/mui-org/material-ui/issues/14943.  I'm in favor of them relying on context instead of `React.cloneElement` to inject props to the menu items if possible.

One way to reuse logic for rendering a menu item without creating a wrapper component would be a render function:

```js
function renderMenuItem({label, ...props}) {
  return <MenuItem {...props}>{label}</MenuItem>
}

function MyComponent() {
  return (
    <Menu>
      {renderMenuItem({label: 'foo'})}
    </Menu>
  )
}
```

**Comment by alexplumb** [comment]
Ah, thanks for the tip - looking at the props it looks like it depends on `tabIndex` being passed to the menu item - all set now!
